/* HOME ACTIONS */
export const GET_HOMEDATA = 'GET_HOMEDATA';
export const GET_HOMEDATA_SUCCESS = 'GET_HOMEDATA_SUCCESS';
export const GET_HOMEDATA_ERROR = 'GET_HOMEDATA_ERROR';

/* LISTING ACTIONS */
export const GET_LISTINGDATA = 'GET_LISTINGDATA';
export const GET_LISTINGDATA_SUCCESS = 'GET_LISTINGDATA_SUCCESS';
export const GET_LISTINGDATA_ERROR = 'GET_LISTINGDATA_ERROR';

/* PRODUCT ACTIONS */
export const GET_PRODUCTDATA = 'GET_PRODUCTDATA';
export const GET_PRODUCTDATA_SUCCESS = 'GET_PRODUCTATA_SUCCESS';
export const GET_PRODUCTDATA_ERROR = 'GET_PRODUCTDATA_ERROR';


/* CART ACTIONS */
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const EMPTY_CART = 'EMPTY_CART';



/* FAVORITE ACTIONS */
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const REMOVE_FROM_FAVORITE = 'REMOVE_FROM_FAVORITE';
export const EMPTY_FAVORITE = 'EMPTY_FAVORITE';